<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Browse Wishlist_product-one-thumb</name>
   <tag></tag>
   <elementGuidId>4d4efef5-b26f-4ed8-9fdd-89d89898acc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='noo-site']/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.noo-product-item.one.noo-product-sm-4.not_featured.post-1467.product.type-product.status-publish.has-post-thumbnail.product_cat-bodycon-dresses.product_tag-bodycon-dresses.product_tag-women.has-featured.instock.shipping-taxable.purchasable.product-type-variable > div.noo-product-inner > div.noo-product-thumbnail > div.noo-product-slider.owl-carousel.owl-theme > div.owl-wrapper-outer.autoHeight > div.owl-wrapper > div.owl-item.active > a.hover-device > img.product-one-thumb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7d217ff0-a3f3-4af5-9a0d-a49a0b2b6c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>5d35f942-c293-4e3a-ae61-984e91f6f5e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>8d5a033b-a8c6-4a8f-8b4d-52cfc4af7b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://shop.demoqa.com/wp-content/uploads/2019/04/white-bandage-cut-out-bodycon-mini-dress-1-300x300.jpg</value>
      <webElementGuid>566278d8-906a-4b1e-b4d7-9e282383d801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-one-thumb</value>
      <webElementGuid>dc74e773-b624-4e36-a914-1e5a300a25a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>90b841ad-1754-405e-9210-047b2d6f51d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://shop.demoqa.com/wp-content/uploads/2019/04/white-bandage-cut-out-bodycon-mini-dress-1-300x300.jpg 300w, https://shop.demoqa.com/wp-content/uploads/2019/04/white-bandage-cut-out-bodycon-mini-dress-1-150x150.jpg 150w, https://shop.demoqa.com/wp-content/uploads/2019/04/white-bandage-cut-out-bodycon-mini-dress-1-650x650.jpg 650w, https://shop.demoqa.com/wp-content/uploads/2019/04/white-bandage-cut-out-bodycon-mini-dress-1-100x100.jpg 100w</value>
      <webElementGuid>7d73925e-1408-4c45-b5fa-90445a40ac76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 300px) 100vw, 300px</value>
      <webElementGuid>8d9a9069-3223-46b5-8637-6f1982bd7b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;noo-site&quot;)/div[@class=&quot;noo-container-shop noo-shop-wrap&quot;]/div[@class=&quot;noo-row&quot;]/div[@class=&quot;noo-md-12 one&quot;]/div[@class=&quot;products noo-row&quot;]/div[@class=&quot;noo-product-item one noo-product-sm-4 not_featured post-1467 product type-product status-publish has-post-thumbnail product_cat-bodycon-dresses product_tag-bodycon-dresses product_tag-women has-featured  instock shipping-taxable purchasable product-type-variable&quot;]/div[@class=&quot;noo-product-inner&quot;]/div[@class=&quot;noo-product-thumbnail&quot;]/div[@class=&quot;noo-product-slider owl-carousel owl-theme&quot;]/div[@class=&quot;owl-wrapper-outer autoHeight&quot;]/div[@class=&quot;owl-wrapper&quot;]/div[@class=&quot;owl-item active&quot;]/a[@class=&quot;hover-device&quot;]/img[@class=&quot;product-one-thumb&quot;]</value>
      <webElementGuid>f3a46f72-7694-4d5f-bcb1-a0c9d2a00b60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='noo-site']/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/div/div/a/img</value>
      <webElementGuid>37dfd6e3-224d-4d7d-a77a-fac06931deeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://shop.demoqa.com/wp-content/uploads/2019/04/white-bandage-cut-out-bodycon-mini-dress-1-300x300.jpg')]</value>
      <webElementGuid>52eca337-2c98-4e4d-9c02-137af5811caf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/a/img</value>
      <webElementGuid>52d9ae2e-bb9e-4995-bf01-35681a4b32f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://shop.demoqa.com/wp-content/uploads/2019/04/white-bandage-cut-out-bodycon-mini-dress-1-300x300.jpg']</value>
      <webElementGuid>03e9c334-bcba-4143-867e-8db544c8adb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
