<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Add to Wishlist_product-one-thumb</name>
   <tag></tag>
   <elementGuidId>81ec53d6-bf93-4e7c-8704-6d57f0b675ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='noo-site']/div[2]/div[2]/div/div/div[10]/div/div/div[2]/div/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.noo-product-item.one.noo-product-sm-4.not_featured.post-1219.product.type-product.status-publish.has-post-thumbnail.product_cat-dress.product_cat-midi-dresses.product_tag-dress.product_tag-midi.product_tag-women.has-featured.instock.shipping-taxable.purchasable.product-type-variable > div.noo-product-inner > div.noo-product-thumbnail > div.noo-product-slider.owl-carousel.owl-theme > div.owl-wrapper-outer.autoHeight > div.owl-wrapper > div.owl-item.active > a.hover-device > img.product-one-thumb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f6e5f49f-b224-4754-865c-d5049c463a4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>43304651-f691-4bf1-8c50-c56b48e27b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>9c10fc25-31f8-4d48-80e7-2169d6b96c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://shop.demoqa.com/wp-content/uploads/2019/04/rust-shimmer-snake-bodycon-midaxi-dress-300x300.jpg</value>
      <webElementGuid>7df504f0-b645-4be0-8db8-5efa82389449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-one-thumb</value>
      <webElementGuid>f8d10292-1475-44a8-a1da-65dd7db4d4d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>20614e8e-6551-4a27-9ab5-2a5d64b2e294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://shop.demoqa.com/wp-content/uploads/2019/04/rust-shimmer-snake-bodycon-midaxi-dress-300x300.jpg 300w, https://shop.demoqa.com/wp-content/uploads/2019/04/rust-shimmer-snake-bodycon-midaxi-dress-150x150.jpg 150w, https://shop.demoqa.com/wp-content/uploads/2019/04/rust-shimmer-snake-bodycon-midaxi-dress-650x650.jpg 650w, https://shop.demoqa.com/wp-content/uploads/2019/04/rust-shimmer-snake-bodycon-midaxi-dress-100x100.jpg 100w</value>
      <webElementGuid>3468815e-af51-4556-99ba-26aa7d1d7280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 300px) 100vw, 300px</value>
      <webElementGuid>fa33190e-8a51-4458-8d1f-e663346abce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;noo-site&quot;)/div[@class=&quot;noo-container-shop noo-shop-wrap&quot;]/div[@class=&quot;noo-row&quot;]/div[@class=&quot;noo-md-12 one&quot;]/div[@class=&quot;products noo-row&quot;]/div[@class=&quot;noo-product-item one noo-product-sm-4 not_featured post-1219 product type-product status-publish has-post-thumbnail product_cat-dress product_cat-midi-dresses product_tag-dress product_tag-midi product_tag-women has-featured  instock shipping-taxable purchasable product-type-variable&quot;]/div[@class=&quot;noo-product-inner&quot;]/div[@class=&quot;noo-product-thumbnail&quot;]/div[@class=&quot;noo-product-slider owl-carousel owl-theme&quot;]/div[@class=&quot;owl-wrapper-outer autoHeight&quot;]/div[@class=&quot;owl-wrapper&quot;]/div[@class=&quot;owl-item active&quot;]/a[@class=&quot;hover-device&quot;]/img[@class=&quot;product-one-thumb&quot;]</value>
      <webElementGuid>2bf350b5-1547-4adf-8c5c-43367aedbb37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='noo-site']/div[2]/div[2]/div/div/div[10]/div/div/div[2]/div/div/div/a/img</value>
      <webElementGuid>4a158711-99e8-4e9a-9cdc-f2862ae3d4ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://shop.demoqa.com/wp-content/uploads/2019/04/rust-shimmer-snake-bodycon-midaxi-dress-300x300.jpg')]</value>
      <webElementGuid>88600419-05a4-4492-b613-b094fe16f94a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div[2]/div/div/div/a/img</value>
      <webElementGuid>4a4ebd02-a85c-47a1-a77a-288149ed6a9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://shop.demoqa.com/wp-content/uploads/2019/04/rust-shimmer-snake-bodycon-midaxi-dress-300x300.jpg']</value>
      <webElementGuid>b0244f37-47da-43d3-adaf-98d5be2749d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
