<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__billing_city</name>
   <tag></tag>
   <elementGuidId>ab3685ef-a5b5-4289-b211-1e88f27af070</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billing_city']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#billing_city</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2d3640c-3ed5-42b4-a89f-029caa9fd490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d9e79c9b-f524-41d6-b5d4-5ba0fbe650b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text </value>
      <webElementGuid>3bc398d9-7ad8-467e-bf89-a37b6e9ec96b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing_city</value>
      <webElementGuid>bca5a0ee-1bb3-43b8-a43a-8361007b393d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing_city</value>
      <webElementGuid>8f96e017-b570-4298-91b1-dbaafa90d442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>address-level2</value>
      <webElementGuid>61d56964-ea83-4595-abff-46ddc7860ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_city&quot;)</value>
      <webElementGuid>8f3be0a2-bd45-431c-8baa-3dfda0161b69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billing_city']</value>
      <webElementGuid>fa2985c0-c4d8-48d1-8c91-3b4b8b2e57d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_city_field']/span/input</value>
      <webElementGuid>49e26e9c-ae93-4f00-8afc-b3a904026e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[7]/span/input</value>
      <webElementGuid>97ddf80d-feaa-4a46-a764-790ebc6a928d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'billing_city' and @id = 'billing_city']</value>
      <webElementGuid>e2f0075e-eade-4f56-8d84-a09947471802</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
