<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Type and Press Enter to Search_s</name>
   <tag></tag>
   <elementGuidId>ea587d1e-e683-43be-9974-f1af8499b79d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='s']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;s&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d2b8f524-9507-4b3d-b42e-869178573e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>f7a6fd9a-ac5d-45b1-a170-ecc35e0025bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>s</value>
      <webElementGuid>288d2030-b274-452f-8719-044628dadb39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6a1d661d-ee4e-4dd0-8dbc-2903e359e728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;noo-site&quot;)/header[@class=&quot;noo-header fixed_top header-2&quot;]/div[@class=&quot;search-header search-header-eff&quot;]/div[@class=&quot;noo-container&quot;]/form[@class=&quot;form-horizontal noo-mebla-searchform&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>63118982-8df6-425e-afa0-5b5accdaa19b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='s']</value>
      <webElementGuid>6cca7cec-7c18-4ac3-838d-51a914a489b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='noo-site']/header/div[3]/div[2]/form/input</value>
      <webElementGuid>9b7e94ff-15d8-43f7-946a-c870cf945055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f6036980-6623-4a17-b615-22515aa9cc90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @name = 's']</value>
      <webElementGuid>73e6a8e5-1ba2-41bd-8b60-a9c9b6ba68f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
