<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Add to Wishlist_product-one-thumb_1</name>
   <tag></tag>
   <elementGuidId>43a77d4b-3298-4600-bb55-ca7cba7ee1e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='noo-site']/div[2]/div[2]/div/div/div[9]/div/div/div[2]/div/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.noo-product-item.one.noo-product-sm-4.not_featured.post-1225.product.type-product.status-publish.has-post-thumbnail.product_cat-dress.product_cat-midi-dresses.product_tag-dress.product_tag-midi.product_tag-women.has-featured.first.instock.sale.shipping-taxable.purchasable.product-type-variable > div.noo-product-inner > div.noo-product-thumbnail > div.noo-product-slider.owl-carousel.owl-theme > div.owl-wrapper-outer.autoHeight > div.owl-wrapper > div.owl-item.active > a.hover-device > img.product-one-thumb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>80dc12f1-ea6f-49d2-a9c4-570bcf2a25e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>fae1ba07-39a6-4062-adff-c37e7fba7add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>f2ac7bd3-f824-47d4-bfb5-4591fad96c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://shop.demoqa.com/wp-content/uploads/2019/04/black-satin-one-shoulder-cut-out-midi-dress-300x300.jpg</value>
      <webElementGuid>bd819701-b933-4ffa-a1c9-8bb01566b61f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-one-thumb</value>
      <webElementGuid>0beeb089-365e-40cb-b448-f1ca6ddafe7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>f7946964-f9aa-455d-a69b-376b5d4f6090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://shop.demoqa.com/wp-content/uploads/2019/04/black-satin-one-shoulder-cut-out-midi-dress-300x300.jpg 300w, https://shop.demoqa.com/wp-content/uploads/2019/04/black-satin-one-shoulder-cut-out-midi-dress-150x150.jpg 150w, https://shop.demoqa.com/wp-content/uploads/2019/04/black-satin-one-shoulder-cut-out-midi-dress-650x650.jpg 650w, https://shop.demoqa.com/wp-content/uploads/2019/04/black-satin-one-shoulder-cut-out-midi-dress-100x100.jpg 100w</value>
      <webElementGuid>6a702936-547a-4a77-a258-457f470f4d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 300px) 100vw, 300px</value>
      <webElementGuid>1bcdfd93-4989-481a-9c2b-80ca74c3f570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;noo-site&quot;)/div[@class=&quot;noo-container-shop noo-shop-wrap&quot;]/div[@class=&quot;noo-row&quot;]/div[@class=&quot;noo-md-12 one&quot;]/div[@class=&quot;products noo-row&quot;]/div[@class=&quot;noo-product-item one noo-product-sm-4 not_featured post-1225 product type-product status-publish has-post-thumbnail product_cat-dress product_cat-midi-dresses product_tag-dress product_tag-midi product_tag-women has-featured first instock sale shipping-taxable purchasable product-type-variable&quot;]/div[@class=&quot;noo-product-inner&quot;]/div[@class=&quot;noo-product-thumbnail&quot;]/div[@class=&quot;noo-product-slider owl-carousel owl-theme&quot;]/div[@class=&quot;owl-wrapper-outer autoHeight&quot;]/div[@class=&quot;owl-wrapper&quot;]/div[@class=&quot;owl-item active&quot;]/a[@class=&quot;hover-device&quot;]/img[@class=&quot;product-one-thumb&quot;]</value>
      <webElementGuid>0ea91971-faa2-417a-ab3e-1aa78228bb16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='noo-site']/div[2]/div[2]/div/div/div[9]/div/div/div[2]/div/div/div/a/img</value>
      <webElementGuid>cd05e834-e725-4326-911e-8410396ed8d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://shop.demoqa.com/wp-content/uploads/2019/04/black-satin-one-shoulder-cut-out-midi-dress-300x300.jpg')]</value>
      <webElementGuid>ad42ffee-6230-4340-a668-1e31ed004b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div[2]/div/div/div/a/img</value>
      <webElementGuid>ff9f1ef2-4656-4c56-9211-efd59d35e376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://shop.demoqa.com/wp-content/uploads/2019/04/black-satin-one-shoulder-cut-out-midi-dress-300x300.jpg']</value>
      <webElementGuid>35404adc-f266-4a3e-b01b-02712d4cd7be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
