<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Choose an optionLargeMediumSmall</name>
   <tag></tag>
   <elementGuidId>443d8991-b2e3-42ea-ba2e-72dfe1e662d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='pa_size']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pa_size</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>00b47f48-9c98-438a-a688-b017a53e75b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pa_size</value>
      <webElementGuid>8c0a06fc-61ad-48d1-bbef-0ba8b0c68f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>attribute_pa_size</value>
      <webElementGuid>1c5d1bb4-6b9e-4f6f-95bc-b345ffd0377d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attribute_name</name>
      <type>Main</type>
      <value>attribute_pa_size</value>
      <webElementGuid>343c27a2-bd8f-423d-b4b9-c1918aaa2a86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-show_option_none</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>1cd5fcf1-4502-4f7d-8d7d-0f26f97642c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose an optionLargeMediumSmall</value>
      <webElementGuid>68174a3e-6db4-42ef-85e4-9155fcc45d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pa_size&quot;)</value>
      <webElementGuid>685fd1be-776b-4236-8d5f-e8edce0ff5cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='pa_size']</value>
      <webElementGuid>856e85d0-a1aa-4241-9d66-2c532dbf8367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-1219']/div/div[2]/form/table/tbody/tr[2]/td/select</value>
      <webElementGuid>b51c4030-576e-475f-80d0-93f378371765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size'])[1]/following::select[1]</value>
      <webElementGuid>390ae5ba-62ac-4a25-9361-c7dc715838f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color'])[1]/following::select[2]</value>
      <webElementGuid>831ec810-83d3-4f3c-a251-102f70f7bdae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QTY'])[1]/preceding::select[1]</value>
      <webElementGuid>f681d382-94b6-40f1-9496-69715c3287e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to cart'])[1]/preceding::select[1]</value>
      <webElementGuid>52619bc9-99cf-46d6-a52d-feca9470a785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/select</value>
      <webElementGuid>cd4fda93-d9cf-41ff-b1da-afabbe989b0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'pa_size' and @name = 'attribute_pa_size' and (text() = 'Choose an optionLargeMediumSmall' or . = 'Choose an optionLargeMediumSmall')]</value>
      <webElementGuid>f3b54828-fc98-43a1-ae99-fd462a11e1fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
